source "https://supermarket.getchef.com"

cookbook "apt"
cookbook "postfix"
cookbook "chef-server"
cookbook "jenkins"
cookbook "mysql", "~> 5.6.0"
cookbook "database", "~> 2.3.0"
cookbook "mysql-chef_gem", "~> 0.0.2"

cookbook "jira", path: "chef-repo/cookbooks/jira"
cookbook "mysql-backup", path: "chef-repo/cookbooks/mysql-backup"
cookbook "reverse-proxy", path: "chef-repo/cookbooks/reverse-proxy"
cookbook "stash", path: "chef-repo/cookbooks/stash"
cookbook "bamboo", path: "chef-repo/cookbooks/bamboo"
cookbook "storage", path: "chef-repo/cookbooks/storage"
