@description = "Kwaai Oak DevOps"
@stack_name = "devops"
@domain = ""
@debug = ""
@devops_bucket = ""
@cloud     = 'aws'
@availability_zone = "us-west-2a"
@key_name = ""
@image_id = "ami-57e8d767"
@knife_config = ""
@berks_config = ""
@aws_access_key_id      = ""
@aws_secret_access_key  = ""
@aws_instance_type      = "m3.large"
@aws_disk_size = 15
@services = [ 'jenkins', 'jira', 'chef', 'stash', 'bamboo' ]
