default['reverse-proxy']['apps']                               = [ ]
default['reverse-proxy']['ssl']['enabled']                     = true
default['reverse-proxy']['ssl']['certificate_file']            = '/etc/ssl/local.kwaaioak.com/server.pem'
default['reverse-proxy']['ssl']['certificate_key_file']        = '/etc/ssl/local.kwaaioak.com/server.key'
default['reverse-proxy']['ssl']['certificate_chain_file']      = '/etc/ssl/local.kwaaioak.com/server.pem'
default['reverse-proxy']['ssl']['certificate']['common_name']  = '*.local.kwaaioak.com'
default['reverse-proxy']['ssl']['certificate']['country']      = 'US'
default['reverse-proxy']['ssl']['certificate']['state']        = 'California'
default['reverse-proxy']['ssl']['certificate']['city']         = 'Santa Monica'
default['reverse-proxy']['ssl']['certificate']['organization'] = 'Kwaai Oak, Inc.'
default['reverse-proxy']['ssl']['certificate']['department']   = 'Engineering'
