default['storage']['mount_path']              = '/mnt/storage'
default['storage']['dirs']                     = nil
default['storage']['bind_dirs']                = nil
default['storage']['mount_type']               = nil
default['storage']['mount_device']             = '/dev/xvdi'
default['storage']['description']              = nil
default['storage']['aws']['access_key']        = nil
default['storage']['aws']['secret_access_key'] = nil
default['storage']['aws']['volume_id']         = nil
default['storage']['backup']['schedule']            = '0 11 * * *'
default['storage']['backup']['chef_config_file']    = '/etc/chef/zero.rb'
default['storage']['backup']['chef_attrib_file']    = '/etc/chef/snapshot.json'
default['storage']['backup']['log_file']            = '/var/log/snapshot.log'
default['storage']['backup']['log_level']           = 'info'
